name: deploy-website

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Install cairo for social cards
      run: |
        sudo apt-get update
        sudo apt-get install -y libcairo2-dev

    - name: Install dependencies
      run: uv sync

    - name: Build the site
      run: |
        uv run mkdocs build
        cp site/feed_rss_created.xml site/feed.xml
        cp site/feed_rss_created.xml site/atom.xml

    - if: ${{ github.ref == 'refs/heads/main' }}
      name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        cname: matthewrocklin.com
